### ISSUE TITLE
Check shows as Down in Web Service Checks overview

### ISSUE THREAD

**Issue by terrytibbles** [Cacti/plugin_webseer#10]
Despite the check completing successfully, the monitor still shows as Down in the Web Service Checks overview. The logs for the same time say that the 'down devices' is 0.

`2017-05-22 17:25:06 - SYSTEM WEBSEER STATS: Total Time:0.019, Service Checks:1, Servers:0
2017-05-22 17:25:05 - SYSTEM THOLD STATS: Time:0.0247 Tholds:0 TotalDevices:2 DownDevices:0 NewDownDevices:0
2017-05-22 17:25:05 - SYSTEM STATS: Time:4.2527 Method:cmd.php Processes:1 Threads:N/A Hosts:2 HostsPerProcess:2 DataSources:6 RRDsProcessed:6`

![web-service-checks-1](https://cloud.githubusercontent.com/assets/25575702/26301822/e8531cac-3f14-11e7-9fc0-4a977b1c9e70.png)

The software versions are as follows:

Apache: 2.4.25
PHP: 7.0.18
MariaDB: 10.1.22
Cacti: 1.1.5
Webseer: 1.0

**Comment by terrytibbles** [comment]
The software versions are as follows:

Apache: 2.4.25
PHP: 7.0.18
MariaDB: 10.1.22
Cacti: 1.1.5
Webseer: 1.0

**Comment by cigamit** [comment]
Well, that is quite odd.

**Comment by aaronwmorris** [comment]
I had the same issue.  I found that a "Response Search String" is required for the check to show as "Up".

I was able to use "HTTP/1.0 200 OK" as a generic string

**Comment by cigamit** [comment]
Okay, get it now.

**Comment by cigamit** [comment]
Resolved.  Thanks for your patience
