### ISSUE TITLE
Feature Request: Integrate Proxy Setting 

### ISSUE THREAD

**Issue by jagmeetbhinder** [Cacti/plugin_webseer#12]
It would be great if you can add proxy setting for this plugin.

**Comment by cigamit** [comment]
Resolved in 2.0.  Please install and test.

**Comment by jagmeetbhinder** [comment]
Github online plugin is 1.1. From where I can download 2.0?

**Comment by jagmeetbhinder** [comment]
Never mind, I was able to resolve this with manual download.
