### ISSUE TITLE
Notify accounts - not showing all account

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_webseer#14]
On webseer setting not all account I can select for notify.
I try found sql code that found user email.

**Comment by pautiina** [comment]
OK, problem not on this plugin.
I think problem on [https://github.com/Cacti/plugin_thold](plugin_thold)

**Comment by pautiina** [comment]
Problem on this:
`function thold_update_contacts() {`
this function run only when edit device thold.

**Comment by cigamit** [comment]
Resolved.  Thanks for the pull request!
