### ISSUE TITLE
Notification email not sent

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_webseer#16]
When the "Notify Accounts" user(s) is selected and a down trigger is activated, emails are not being sent to "Notify Accounts" defined recipients.

Cacti LOG event (this is with users selected in "Notify Accounts"):

05/07/2017 15:20:52 - WEBSEER ERROR: No users to send WEBSEER Notification for OLD Cacti

However, if there are emails present in the "Extra Alert Emails", they are sent out successfully, and no log message is generated except for the WEBSEER STATS upon polling completion.

**Comment by cigamit** [comment]
Resolved.  Sorry for the delay.
