### ISSUE TITLE
Feature Request : Historic Graphs

### ISSUE THREAD

**Issue by jagmeetbhinder** [Cacti/plugin_webseer#17]
This is great plugin to monitor the website URL. It would be great if you can add historic graphing with this tool just like murlin.

Thanks

**Comment by netniV** [comment]
@jagmeetbhinder or @terrytibbles - Could one you give more of an explanation of what you are after?

**Comment by jagmeetbhinder** [comment]
Apologies, for little information in the request. I requested URLs graphs with historical stats, like connect time, DNS resolution time and page download time etc.
With historic graphs/number I can go back and compare the values between two time frames.

**Comment by xmacan** [comment]
It is resolved in Servcheck plugin. Servcheck is based on webseer, has more tests, logs, ...
https://github.com/Cacti/plugin_servcheck
