### ISSUE TITLE
Webseer showing the wrong value under webseer_servers_edit

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_webseer#19]
Hi there,

First screenshot shows the current settings

![webseer_issue 19_1](https://user-images.githubusercontent.com/13456559/29442898-89957c92-8428-11e7-9168-be61ac74957b.png)

Second screenshot shows the server enabled box unchecked after I click to edit the server

![webseer_issue 19_2](https://user-images.githubusercontent.com/13456559/29442910-a0ddd35e-8428-11e7-89a6-c40b152d128d.png)

**Comment by cigamit** [comment]
Resolved.  Thanks for catching and sorry for the delay.  Busy as always.
