### ISSUE TITLE
Deprecated PHP function

### ISSUE THREAD

**Issue by frankcrawford** [Cacti/plugin_webseer#2]
When I run webseer downloaded with the latest version from GitHub I get the following messages log in cacti's log file:
`2017-03-11 21:30:30 - ERROR PHP DEPRECATED in  Plugin 'webseer': Methods with the same name as their class will not be constructors in a future version of PHP; mxlookup has a deprecated constructor in file: /usr/share/cacti/plugins/webseer/functions.php  on line: 479
2017-03-11 21:30:30 - CMDPHP PHP ERROR Backtrace: (/plugins/webseer/webseer_process.php: 41 include_once)(/plugins/webseer/webseer_process.php: 41 CactiErrorHandler)(/lib/functions.php: 4272 cacti_debug_backtrace)`

**Comment by cigamit** [comment]
Resolved thanks for reporting!

**Comment by frankcrawford** [comment]
Thanks, that has fixed the messages.
