### ISSUE TITLE
plugin_webseer_proxies table is not being created

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_webseer#20]
See clog errors below

```

2017/11/08 13:08:53 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') unsigned default '80', `username` varchar(40) default '', `password` varchar' at line 1
--
2017/11/08 13:08:53 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'CREATE TABLE IF NOT EXISTS `plugin_webseer_proxies` ( `id` int(11) unsigned NOT NULL auto_increment, `name` varchar(30) default '', `hostname` varchar(64) default '', `port` mediumint() unsigned default '80', `username` varchar(40) default '', `password` varchar(60) default '', PRIMARY KEY (`id`), KEY `hostname` (`hostname`), KEY `name` (`name`)) ENGINE=InnoDB COMMENT='Holds WebSeer Proxy Information for Connections''

```

**Comment by lbsou** [comment]
Same problem.

**Comment by cigamit** [comment]
Just committed the fix.  Create the table manually from the setup.php to use if you won't want to uninstall first.

**Comment by lbsou** [comment]
Hi, 

I just did a git clone and reinstalled it.

But I got the same error. Seems like the table is still not created...

2017/11/23 14:12:28 - CMDPHP Validation Error, Variable:id, Value:'0' Backtrace: (/plugins/webseer/webseer_proxies.php: 46 proxy_edit)(/plugins/webseer/webseer_proxies.php: 160 get_filter_request_var)(/lib/html_utility.php: 435 die_html_input_error)(/lib/html_validate.php: 60 cacti_debug_backtrace)
--
2017/11/23 14:12:28 - DBCALL ERROR: SQL Save Failed for Table 'plugin_webseer_proxies'. SQL:'INSERT INTO plugin_webseer_proxies (`id`, `name`, `hostname`, `http_port`, `https_port`, `username`, `password`) VALUES ('0', 'PROXY', 'HIDDEN', '8080', '8080', '', '') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `hostname`=VALUES(`hostname`), `http_port`=VALUES(`http_port`), `https_port`=VALUES(`https_port`), `username`=VALUES(`username`), `password`=VALUES(`password`)'
2017/11/23 14:12:28 - CMDPHP SQL Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 1001 _db_replace)(/lib/database.php: 948 db_execute)(/lib/database.php: 135 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
2017/11/23 14:12:28 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'cacti1.plugin_webseer_proxies' doesn't exist
2017/11/23 14:12:28 - DBCALL ERROR: A DB Exec Failed!, Error:1146, SQL:'INSERT INTO plugin_webseer_proxies (`id`, `name`, `hostname`, `http_port`, `https_port`, `username`, `password`) VALUES ('0', 'PROXY', 'HIDDEN', '8080', '8080', '', '') ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `hostname`=VALUES(`hostname`), `http_port`=VALUES(`http_port`), `https_port`=VALUES(`https_port`), `username`=VALUES(`username`), `password`=VALUES(`password`)'
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: password in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: password in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: password in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: password in file: /usr/share/cacti1/lib/database.php on line: 975
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: username in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: username in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: username in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: username in file: /usr/share/cacti1/lib/database.php on line: 975
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: https_port in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: https_port in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: https_port in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: https_port in file: /usr/share/cacti1/lib/database.php on line: 975
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: http_port in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: http_port in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: http_port in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: http_port in file: /usr/share/cacti1/lib/database.php on line: 975
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: hostname in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: hostname in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: hostname in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: hostname in file: /usr/share/cacti1/lib/database.php on line: 975
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: name in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: name in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: name in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: name in file: /usr/share/cacti1/lib/database.php on line: 975
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 978 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti1/lib/database.php on line: 978
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 977 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti1/lib/database.php on line: 977
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 976 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti1/lib/database.php on line: 976
2017/11/23 14:12:28 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 37 proxy_form_save)(/plugins/webseer/webseer_proxies.php: 145 sql_save)(/lib/database.php: 975 CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
2017/11/23 14:12:28 - ERROR PHP NOTICE: Undefined index: id in file: /usr/share/cacti1/lib/database.php on line: 975

**Comment by lbsou** [comment]
![cacti_webseer](https://user-images.githubusercontent.com/30626084/33186666-2c75dc82-d059-11e7-8e96-d85de874bdcd.PNG)

**Comment by cigamit** [comment]
Well that's odd.  Updating, but weird.

**Comment by cigamit** [comment]
Try again...

**Comment by lbsou** [comment]
Ok, it work now! but I have another error
![cacti_webseer](https://user-images.githubusercontent.com/30626084/33187053-f5ad9df8-d05c-11e7-88c6-ad6c9b31496e.PNG)

**Comment by lbsou** [comment]
![cacti_webseer](https://user-images.githubusercontent.com/30626084/33187080-277bacb2-d05d-11e7-8b3f-3c7581901229.PNG)

**Comment by lbsou** [comment]
Happy Thanksgiving too!

So now, it is polling but : 

If I use a proxy, I get : Moved Permanently

The server I use for the polling is whitelisted in the proxy.
I tried several website.
If I dont use proxy, it appear as  : OK

**Comment by cigamit** [comment]
The Moved Permanently should be resolved now.  If so, please close.

**Comment by jpobeda** [comment]
I'll test it and update here

**Comment by jpobeda** [comment]
Table is now getting created.

But I've set up 2 URLs. 1 with proxy and 1 without


```
2017/12/05 15:51:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
--
2017/12/05 15:51:23 - ERROR PHP NOTICE in Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti-1.1.21/plugins/webseer/webseer_proxies.php on line: 409
05/Dec/2017 15:43:45 - WEBSEER ERROR: No users to send WEBSEER Notification for IEEE OUI
05/Dec/2017 15:43:45 - WEBSEER ERROR: No users to send WEBSEER Notification for IEEE OUI
05/Dec/2017 15:36:53 - WEBSEER ERROR: No users to send WEBSEER Notification for XXXXXXXX
05/Dec/2017 15:36:53 - WEBSEER ERROR: No users to send WEBSEER Notification for XXXXXXXX
2017/12/05 15:36:33 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2017/12/05 15:36:33 - ERROR PHP NOTICE in Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti-1.1.21/plugins/webseer/webseer_proxies.php on line: 409
2017/12/05 15:34:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2017/12/05 15:34:26 - ERROR PHP NOTICE in Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti-1.1.21/plugins/webseer/webseer_proxies.php on line: 409
2017/12/05 15:33:21 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2017/12/05 15:33:21 - ERROR PHP NOTICE in Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti-1.1.21/plugins/webseer/webseer_proxies.php on line: 409
```
I'll update more details tomorrow because it doesn't look like it's even trying to use the proxy but checking the proxy as the url.

Let me know if you want me to close this one and open a new one for the other ones.

**Comment by jpobeda** [comment]
Solved
