### ISSUE TITLE
Layout issue: Long URL pushes other columns off the screen

### ISSUE THREAD

**Issue by ITATG** [Cacti/plugin_webseer#22]
![image](https://user-images.githubusercontent.com/35332688/34829295-7ca67362-f6e0-11e7-8f08-5c1785572457.png)

It would seem if a URLis very long, it pushes the other columns off the screen.  Tested with Version 1.0 and 2.0

**Comment by ITATG** [comment]
My solution is to cut and put ... if characters are higher than 58.
On webseer.php, row 391:
if ($row['type'] == 'http') {
				form_selectable_cell("<a class='linkEditMain' href='" .$row['url'] . "' target=_new>" . mb_strimwidth($row['url'],0,58, "...") . '</a>', $row['id']);

It fits for browsers zoom 100%. I tried with CSS but not working I don't know why. With CSS is cleaner I guess

![image](https://user-images.githubusercontent.com/35332688/34836329-e2089aa2-f6f7-11e7-99ed-dc4a7aec5c3b.png)

Thank you

**Comment by cigamit** [comment]
Please test my solution.  The URL is hidden, but if you click on the Name, you will open the window.  Close if acceptable.

**Comment by cigamit** [comment]
I'm just going to close.  Bark if you feel it should be done differently.

**Comment by ITATG** [comment]
Perfect! Thank you!
