### ISSUE TITLE
Connection error URL

### ISSUE THREAD

**Issue by 701019** [Cacti/plugin_webseer#23]
i have two check list 
1. http://www.test.com/data     check "hello world"
2. http://www.env.con/group    check "Status"

1 always check failed, 

click  http://www.test.com/data  always show http://www.env.con/group  code .... 

help...plz

**Comment by cigamit** [comment]
There is a string match, it performs a search for the response text, make sure you included the snippet of text that you are searching for in the response.  The 200 is not enough, though there was a change lately to allow just the 200 check when the response check string is blank.
