### ISSUE TITLE
Webseer opens wrong URL 

### ISSUE THREAD

**Issue by Lalbee99** [Cacti/plugin_webseer#25]
When in Web Service Checks if you choose an URL in the name column it opens a new browser page with a different URL other than the one choosen.  I am running webseer version: 2.0 with Cacti version 1.1.37

**Comment by hellspawndf** [comment]
Same here

**Comment by netniV** [comment]
As I'm not running webseer currently, can you post the partial URL where you are at, plus a screenshot to help guide me to what i'm looking for?

**Comment by KnoAll** [comment]
Same issue for me.
By 'URL where you are at' I assume you mean the URL of the page where the incorrect link is? If so...
http://cacti/cacti/plugins/webseer/webseer.php
The incorrect target for me is whatever the target of the last web service check you defined.
Does this help?

**Comment by netniV** [comment]
Yes, I think I know what that problem might be.

**Comment by netniV** [comment]
The URL is only updated if the row['type'] is http or dns.  Try doing the following for me:

```sql
SELECT type, COUNT(*) FROM plugin_webseer_urls
GROUP BY type
```

However, the `$url` field was never cleared so it means that the value was still set from a previously valid check.

**Comment by netniV** [comment]
Please download the latest dev version and see if this resolves your issue @Lalbee99 and @KnoAll

**Comment by Lalbee99** [comment]
I installed the updated version. Where as before it would open with the wrong URL now it just opens with a Not Found message (see below) 

Not Found

The requested URL /XXXXXXX/plugins/webseer/Search string not found was not found on this server.

**Comment by netniV** [comment]
Which column do you click on to open the link?

**Comment by Lalbee99** [comment]
Under Checks The Name Field

**Comment by netniV** [comment]
OK, I've pushed another change up.  Please download again.

**Comment by Lalbee99** [comment]
You are back to the original problem where it opens the same URL regardless of which name you select

**Comment by netniV** [comment]
Can you perform the above SQL query for me?  I'm curious as to how this is happening as it's not making much sense to me right now but that may be just because I have a headache at the moment from some other changes ;-)

**Comment by Lalbee99** [comment]
MariaDB [cacti]> SELECT type, COUNT(*) FROM plugin_webseer_urls
    -> GROUP BY type
    -> ;
+------+----------+
| type | COUNT(*) |
+------+----------+
| http |        2 |
+------+----------+
1 row in set (0.00 sec)

MariaDB [cacti]>

**Comment by netniV** [comment]
So I took the plunge and installed, created two urls and replicated the issue. i'll be back later once I see what the actual issue is but it would appear that the URLs are only using the last URL found and I suspect that it is the javascript that is doing it.

**Comment by netniV** [comment]
OK.  So, it was the javascript and I've now patched that too.  Thank you for your patience.

**Comment by Lalbee99** [comment]
You nailed it, good job !

**Comment by KnoAll** [comment]
@netniV Thanks so much! Much appreciated.
