### ISSUE TITLE
Undefined variable 'key' error in webseer_proxies.php

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_webseer#26]
When i'm switching to proxy tab i have these errros into the cacti log:
2018/05/02 11:50:26 - ERROR PHP NOTICE in  Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti/plugins/webseer/webseer_proxies.php  on line: 409
2018/05/02 11:50:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2018/05/02 11:51:05 - ERROR PHP NOTICE in  Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti/plugins/webseer/webseer_proxies.php  on line: 409
2018/05/02 11:51:05 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
2018/05/02 11:52:58 - ERROR PHP NOTICE in  Plugin 'webseer': Undefined variable: key in file: /usr/share/cacti/plugins/webseer/webseer_proxies.php  on line: 409
2018/05/02 11:52:58 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/webseer/webseer_proxies.php: 51 proxies)(/plugins/webseer/webseer_proxies.php: 313 webseer_filter)(/plugins/webseer/webseer_proxies.php: 409 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)

Thanks a lot.

**Comment by netniV** [comment]
I will take a look shortly.

**Comment by netniV** [comment]
So there appears to be a variable $key, and I have no idea where it's come from because its not set in the code anywhere that I can see and there is only one history of the file (which I'm about to check) so I'd be surprised if it was removed.

This is going to take slightly longer than I thought to figure out :)

**Comment by netniV** [comment]
Haha, I take that back, I suddenly realised what this was.  Someone's copy and paste error which is now resolved in the latest development branch.

**Comment by anarkia1976** [comment]
Solved, thanks a lot.
