### ISSUE TITLE
Notification email sent twice with different info

### ISSUE THREAD

**Issue by KnoAll** [Cacti/plugin_webseer#27]
When i have a WSC in alarm, I get two emails with the same subject, but different body text...

Site Recovering: X URL: http://x.x.x.x:x/ Error: Total Time: 0.046805 

and

URL: | http://x.x.x.x:x/
-- | --
Status: | Recovering
Date: | August 23, 2018 - 02:20:55
HTTP Code: | OK

This is both for UP and DOWN messages.
Site Down: X URL: http://x.x.x.x:x/ Error: Search string not found Total Time: 0.037277 
 and
URL: | http://x.x.x.x:x/
-- | --
Status: | Down
Date: | August 23, 2018 - 02:28:05
HTTP Code: | OK
Error: | Search string not found

**Comment by KnoAll** [comment]
Still seeing this. Is there any hope?

**Comment by netniV** [comment]
By the looks of it, that was by design.  Check out lines 33 - 34 in webseer_process.php

**Comment by KnoAll** [comment]
I'm not a developer so I'll have to take your word for it! I can't imagine what the idea was there? the duplication is messy in an inbox with essentially the same info. one or the other, but not both!

**Comment by netniV** [comment]
For now, take out the one you don’t want in your version and I’ll add an option for which to send at a later point.

**Comment by KnoAll** [comment]
So I should be able to comment/remove one or the other of these?

$dir = dirname(__FILE__);
chdir($dir);

**Comment by netniV** [comment]
Err, they aren't the lines i should have referred to.  I meant, 235 - 236

```
plugin_webseer_get_users($results, $url, '');
plugin_webseer_get_users($results, $url, 'text');
```

**Comment by KnoAll** [comment]
Ah, that one I can follow! I commented and tested and all is well. This will do for now, but I look forward to a setting toggle one day!
Thanks!

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.

**Comment by KnoAll** [comment]
I see the new selection! Thanks so much!
Have not had a fired alert yet though.
