### ISSUE TITLE
Status does not change even if it forces the error

### ISSUE THREAD

**Issue by mays1509** [Cacti/plugin_webseer#29]
Good afternoon, even if you force the error of placing a false URL it does not change the status to Down, it is always Up, and of course if it does not change the status it will not send notifications by mail.

Only changes occur in "HTTP Code"

**Comment by netniV** [comment]
I have used a bad url and my check is showing as down.  If you can provide more information that would be useful and make sure you have the latest version.

**Comment by TheWitness** [comment]
No feedback.
