### ISSUE TITLE
allow 'notification lists' for webseer alerts

### ISSUE THREAD

**Issue by KnoAll** [Cacti/plugin_webseer#32]
It would be great to allow the already defined (perhaps for another plugin?) notification lists to be used for the webseer plugin. I do not have user accounts for everyone who gets a notification of a downed device, so it would be great to be able to have mixed notification targets for webseer as well.

**Comment by netniV** [comment]
Threshold's already use notification lists.  Anything else that needs them tends to have a dependancy set for that plugin.  However, I would prefer to have notification lists themselves in the core and that way any plugin can utilise them.

**Comment by KnoAll** [comment]
Yes, it would be great to have the notification lists available in webseer and others!
