### ISSUE TITLE
DISABLING PLUGIN 'webseer'

### ISSUE THREAD

**Issue by eprado22** [Cacti/plugin_webseer#35]
Hi! thanks in advance
I want to use webseer plugin to monitor url availability, but the plugin is automatically deactivated
Cacti version: 1.2.2
OS: Ubuntu Server 18.04

LOG:
2019/02/25 13:05:08 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'webseer'
--
2019/02/25 13:05:07 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/02/25 13:05:07 - ERROR PHP ERROR in Plugin 'webseer': Uncaught ArgumentCountError: Too few arguments to function plugin_webseer_debug(), 1 passed in /opt/cacti/plugins/webseer/poller_webseer.php on line 176 and exactly 2 expected in /opt/cacti/plugins/webseer/functions.php:664 Stack trace: #0 /opt/cacti/plugins/webseer/poller_webseer.php(176): plugin_webseer_debug('Registering Ser...') #1 /opt/cacti/plugins/webseer/poller_webseer.php(94): plugin_webseer_register_server() #2 {main} thrown in file: /opt/cacti/plugins/webseer/functions.php on line: 664

**Comment by netniV** [comment]
This is now in the main development code, please check and close if issue is resolved.
