### ISSUE TITLE
Poller reports backtrace errors when performing webseer checks

### ISSUE THREAD

**Issue by Lalbee99** [Cacti/plugin_webseer#37]
**Describe the bug**
When the cacti poller runs it generates the following errors when performing the webseer checks:

2019/03/14 08:37:05 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/webseer/poller_webseer.php[142]:plugin_webseer_update_servers(), /plugins/webseer/poller_webseer.php[207]:CactiErrorHandler())
2019/03/14 08:37:05 - ERROR PHP WARNING in Plugin 'webseer': Invalid argument supplied for foreach() in file: /cacti/cacti-0.8.8b/plugins/webseer/poller_webseer.php on line: 207 

**To Reproduce**
1. Go to  Logs
2. Click on Show Warnings or Errors 
3. See error

**Expected behavior**
No errors 

**Screenshots**

**Plugin (please complete the following information):**
 - Version: 3.0
 - Source: Github
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Mozilla 
 - Version  52.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lalbee99** [comment]
Unable to attach a screen shot utilizing drag & drop or paste .

**Comment by netniV** [comment]
Your version of Cacti is too low for the plugin.  You need to find an older version of the plugin.

**Comment by Lalbee99** [comment]
My version of cacti is 1.2.2 and the webseer plugin is 3.0

**Comment by Lalbee99** [comment]
General Information
Date 	Thu, 14 Mar 2019 10:23:30 -0400
Cacti Version 	1.2.2
Cacti OS 	unix
RSA Fingerprint 	83:6e:3c:63:23:d1:d1:7e:8b:1f:5f:f5:72:4d:75:8c
NET-SNMP Version 	NET-SNMP version: 5.7.2
RRDtool Version Configured 	1.4.0+
RRDtool Version Found 	1.4.8
Devices 	179
Graphs 	2583
Data Sources 	Script/Command: 390
SNMP Get: 131
SNMP Query: 1919
Script Query: 82
Script Server: 110
Total: 2632
Poller Information
Interval 	300
Type 	SPINE 1.2.2 Copyright 2004-2017 by The Cacti Group
Items 	Action[0]: 4058
Action[1]: 668
Action[2]: 104
Total: 4830
Concurrent Processes 	10
Max Threads 	15
PHP Servers 	5
Script Timeout 	40
Max OID 	60
Last Run Statistics 	Time:123.2908 Method:spine Processes:5 Threads:60 Hosts:158 HostsPerProcess:32 DataSources:4830 RRDsProcessed:0

**Comment by Lalbee99** [comment]
Actions
	
Plugin Name
	
Plugin Description
	
Status
	
Author
	
Requires
	
Version
	
Load Order
	Audit	Audit Plugin for Cacti 	Active 	The Cacti Group 		1.0 	
	Monitor	Device Monitoring 	Active 	The Cacti Group 	Thold 	2.3.4 	
	Mactrack	Device Tracking 	Installed 	The Cacti Group 		4.2 	
	Gexport	Graph Export Package for Cacti 	Installed 	The Cacti Group 		1.4.1 	
	Intropage	Intropage/Dashboard 	Active 	Petr Macek 		1.7 	
	Maint	Maintenance Scheduler 	Active 	The Cacti Group 		1.1 	
	Weathermap	Network Weathermap for Cacti 1.x 	Not Installed 	Howard Jones 		1.0.0dev 	
	Quicktree	QuickTree for Cacti 1.x 	Active 	Howard Jones 		1.0.0 	
	Reportit	Reporting tool for Cacti 	Installed 	The Cacti Group 		1.0 	
	Syslog	Syslog Monitoring 	Active 	The Cacti Group 		2.1 	
	Thold	Thresholds 	Active 	The Cacti Group 		1.0.5 	
	Webseer	Web Service Monitor 	Active 	The Cacti Group 		3.0

**Comment by netniV** [comment]
OK, apologies, the file path led to some confusion: `/cacti/cacti-0.8.8b/plugins/webseer`

**Comment by Lalbee99** [comment]
Sorry it was my original cacti install version. I haven't gotten around to modifying a MySQL backup with a generic path (/cacti) and performing a restore after the upgrade. It is on my to do list.

**Comment by netniV** [comment]
Download the latest development version.  Your line numbers didn't line up with what we have but I have made a guess.  If it cures your problem I'll update the version details accordingly.

**Comment by Lalbee99** [comment]
Good to go no more errors. Good work !
