### ISSUE TITLE
Add custom part of notification e-mail

### ISSUE THREAD

**Issue by petrbalek** [Cacti/plugin_webseer#38]
Hi,
I have idea for RFC - to add into e-mail notification message "custom" part, where we can add some own specific body message.
Thanks
PetrB

**Comment by TheWitness** [comment]
I think the goal is to expand the use of Notification Lists drastically.  This will happen after the develop version of thold is released.

**Comment by xmacan** [comment]
It is resolved in Servcheck plugin. Servcheck is based on webseer, has more tests, logs, ...
https://github.com/Cacti/plugin_servcheck
