### ISSUE TITLE
[WEBSEER - latest source code] - Problem with button - Interface

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_webseer#50]
Hi Guys @xmacan,

i have a problem with web interface, i can't start/stop service for sites with buttons:
![image](https://user-images.githubusercontent.com/1744639/215979276-455b40d6-ee3b-4c25-bf3c-8dd5ccafb567.png)

it's working if you select and the site and the disable it with specific tab:
![image](https://user-images.githubusercontent.com/1744639/215979575-5e335034-02bd-4393-9526-e6b9ef5a9dce.png)

thanks a lot.

**Comment by TheWitness** [comment]
Yea, I broke it big time...

**Comment by TheWitness** [comment]
This is fixed now.  More issues coming in though.
