### ISSUE TITLE
Allow WebSeer service checks to be assigned to a Remote Data Collector

### ISSUE THREAD

**Issue by TheWitness** [Cacti/plugin_webseer#53]
**Is your feature request related to a problem? Please describe.**

Currently, only the Main Data Collector is supported, allow the Remote Data Collectors to be assigned for a service check.

**Describe the solution you'd like**

Fully support Remote Data Collectors for service check assignment.

**Comment by xmacan** [comment]
It is resolved in Servcheck plugin. Servcheck is based on webseer, has more tests, logs, ...
https://github.com/Cacti/plugin_servcheck
