### ISSUE TITLE
Webseer 3.2 - problem with sending email

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_webseer#56]
Someone report it in forum:
https://forums.cacti.net/viewtopic.php?p=290877#p290877

Testing on 1.2.25/3.2 with the same result - no email alert.

**Comment by TheWitness** [comment]
@xmacan, I've added the poller_id option and that might have broke a few things.  Also, the concept of server is going away.

New design supports remote pollers.  Hope that helps...

**Comment by xmacan** [comment]
It is resolved in Servcheck plugin. Servcheck is based on webseer, has more tests, logs, ...
https://github.com/Cacti/plugin_servcheck
