### ISSUE TITLE
Webseer table missing

### ISSUE THREAD

**Issue by KnoAll** [Cacti/plugin_webseer#58]
Getting an error in the logfile for a missing table.
ERROR: A DB Exec Failed!, Error: Table 'cacti.plugin_webseer_contacts' doesn't exist 
CMDPHP SQL Backtrace: (/cli/poller_replicate.php[115]:replicate_out(), /lib/poller.php[1772]:api_plugin_hook_function(), /lib/plugins.php[155]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[276]:webseer_replicate_out(), /plugins/webseer/setup.php[414]:replicate_out_table(), /lib/poller.php[1923]:db_execute(), /lib/database.php[385]:db_execute_prepared())

**Comment by xmacan** [comment]
strange that you haven't table. Try create it manually:
CREATE TABLE IF NOT EXISTS `plugin_webseer_contacts` (
		`id` int(12) NOT NULL auto_increment,
		`user_id` int(12) NOT NULL,
		`type` varchar(32) NOT NULL,
		`data` text NOT NULL,
		PRIMARY KEY (`id`),
		UNIQUE KEY `user_id_type` (`user_id`,`type`),
		KEY `type` (`type`),
		KEY `user_id` (`user_id`))
		ENGINE=InnoDB
		COMMENT='Table of WebSeer contacts'

**Comment by TheWitness** [comment]
Marking closed.  No idea either.

**Comment by KnoAll** [comment]
Creating the table seems to have fixed. Thanks
