### ISSUE TITLE
About  get host's IP address

### ISSUE THREAD

**Issue by horizonlin** [Cacti/plugin_webseer#7]
using the code below:
if (function_exists('gethostname')) {
		$hostname = gethostname();
	}else{
		$hostname = php_uname('n');
	}

	$ipaddress = gethostbyname($hostname);
It always get 127.0.0.1 .  Is it better by using  $config('poller_id')?

**Comment by cigamit** [comment]
It would likely be better to communicate using a token.  Just have to device what that token it.
