### ISSUE TITLE
Poller server don't check URLs

### ISSUE THREAD

**Issue by horizonlin** [Cacti/plugin_webseer#8]
Main server can check URLs, but poller do not  check,   just  check server alive by remote  remote.php  using  HEARTBEAT  parm.

It  is better to record the check result  which  poller server check .

**Comment by horizonlin** [comment]
I have saw issue #1 and know that why didn't  check URLs  by remote remote.php,  This plugins was wrote  seven years ago. I think It should be updated

**Comment by netniV** [comment]
@horizonlin I know it's been a long time, but I just installed the webseer plugin, and then tested a WCF service and it worked OK.  I'm going to close this for now, but if you still have issues, please provide more information and we can reopen it.
